### ISSUE TITLE
Performance counter missing display name

### ISSUE THREAD

**Issue by therealbrucec** [cookdown/ServiceNow-Monitoring-MP#2]
The counter collects data fine but is missing its display name: 
![image](https://user-images.githubusercontent.com/45488930/66296144-d4aff680-e8e4-11e9-8f1d-3cb76de38e89.png)

This causes is to appear to have no rule name in the rules list:
![image](https://user-images.githubusercontent.com/45488930/66296202-ef826b00-e8e4-11e9-92d8-6e7a2ef2c768.png)

**Comment by P2P-Nathan** [comment]
Display name has been added for this.

```
        <DisplayString ElementID="CookdownCommunity.ServiceNow.Monitoring.Performance.Instance.FetchTime">
          <Name>Collect Instance Performance Fetch Time</Name>
          <Description>Tracks how long it took to fetch the data for this instance.</Description>
        </DisplayString>
```
